language: node_js
node_js:
- "stable"
install:
  - npm install
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage