language: node_js
node_js:
- "stable"
install:
  - npm install
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
before_script:
  - createuser godwin -s -U postgres
  - createdb weconnect_test --username=godwin
  - sequelize db:migrate:undo:all
  - sequelize db:migrate
script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage