language: node_js
node_js:
- "stable"
install:
  - npm install
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
  - sequelize db:seed:all
script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage