language: node_js
node_js:
- "stable"
install:
  - npm install
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
addons:
- postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage