language: node_js
node_js:
- "stable"
install:
  - npm install
env:
  - NODE_ENV=test
  - DB_URL_TEST = postgres://dxuksonr:EfqacJhATNlVrIpeiVcUvXeZMNMEl9tq@stampy.db.elephantsql.com:5432/dxuksonr
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage