swagger: '2.0'
info:
  description: WeConnect provides a platform that brings businesses and individuals together. This platform creates awareness for businesses and gives the users the ability to write reviews about the businesses they have interacted with
  version: 1.0.0
  title: Weconnect
  # My Contact Info
  contact:
    email: godwinekuma@gmail.com
basePath: /api/v1

# tags are used for organizing operations
tags:
- name: business
  description: Business operations
- name: auth
  description: Operations for user details
- name: reviews
  description: Operations for reviews

paths:
  /businesses:
    get:
      tags:
      - business
      summary: list all businesses
      description: List all businesses in the application
      produces:
      - application/json
      responses:
        '200':
          description: A list of  businesses in the databse
          examples:
            application/json:
              message: Businesses has been retrieved succesfully
              business:
                businessName: Instrap Solutions Limited
                businessPhone: 08133512053
                businessEmail: info@instrap.com
                businessCategory: Web Development and Graphics
                businessWebsite: https//:instrap.com
                businessDescription: Lorem ipsum dolor sit amet, consectetur adipiscing elit
                businessAddress: 15 Abayomi Street, Surulere, Lagos.
        '404':
          description:  No business found
          examples:
            application/json:
              message: No business has been added to the database
        '500':
          description: Server error 
          examples:
            application/json:
              message: An internal error has occured
    post:
      summary: Register a business
      tags:
       - business
      summary: Add business
      description: Add business to the application
      operationId: add-business
      produces:
      - application/json
      parameters:
      - in: formData
        name: businessName
        type: string
        description: Name of business
        required: true
      - in: formData
        name: businessPhone
        type: string
        description: Business Mobile contact
      - in: formData
        name: businessEmail
        type: string
        description: Email contact of business
      - in: formData
        name: businessCategory
        type: string
        description: Category  of business
      - in: formData
        name: businessWebsite
        type: string
        description: Web Url of business
      - in: formData
        name: businessDescription
        type: string
        description: summary of waht a business does
      - in: formData
        name: businessAddress
        type: string
        description: Location of business
      responses:
        '201':
          description: Created Business Successfully
          examples:
            application/json:
              message: New Business Added
              business:
                businessName: Instrap Solutions Limited
                businessPhone: 08133512053
                businessEmail: info@instrap.com
                businessCategory: Web Development and Graphics
                businessWebsite: https//:instrap.com
                businessDescription: Lorem ipsum dolor sit amet, consectetur adipiscing elit
                businessLocation: 15 Abayomi Street, Surulere, Lagos.
        '400':
          description: Invalid input
          examples:
            application/json:
              message: Business Name Missing
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: You need to sign in to continue or sign up to get started
        '403':
          description: Forbidden request
          examples:
            application/json:
              message: Business already exist
        '500':
          description: Internal Server error
          examples:
            application/json:
              message: An error has occured
        security:
        - weconnect_auth:
            - read:userId
  /businesses?location={location}:
    get:
      tags:
      - business
      summary: list businesses in a location
      operationId: location
      description: List all busnesses in a given location
      produces:
      - application/json
      parameters:
        - name: location
          in: path
          required: true
          description: The location of the business to retrieve
          type: string
      responses:
        '200':
          description: A list of businesses in a location
          examples:
            application/json:
              message: Business in the location has been retrived successfully
        '404':
          description: A list of businesses in a location
          examples:
            application/json:
              message: No business was found in this location
        '500':
          description: Server Error
          examples:
            application/json:
              message: Internal Server error
  /businesses?category={category}:
    get:
      tags:
      - business
      summary: list all businesses in a business category
      operationId: category
      description: List all businesses in a category
      produces:
      - application/json
      parameters:
        - name: category
          in: path
          required: true
          description: The category of the business to retrieve
          type: string
      responses:
        '200':
          description: A list of businesses in a category
          examples:
            application/json:
              message: Businesses in the location has been retrived successfully
        '404':
          description: A list of businesses in a category
          examples:
            application/json:
              message: No business was found in this category
        '500':
          description: Server Error
          examples:
            application/json:
              message: Internal Server error
  /businesses/{id}:
    get:
      summary: Info for a specific business
      tags:
        - business
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the business to retrieve
          type: integer
      responses:
        '200':
          description: Success, business found
          examples:
            application/json:
              message: Business details retrieved succesfully
              business:
                businessName: Instrap Solutions Limited
                businessPhone: 08133512053
                businessEmail: info@instrap.com
                businessCategory: Web Development and Graphics
                businessWebsite: https//:instrap.com
                businessDescription: Lorem ipsum dolor sit amet, consectetur adipiscing elit
                businessLocation: 15 Abayomi Street, Surulere, Lagos.
        '404':
          description: A list of businesses in a category
          examples:
            application/json:
              message: No business was found in this category
        '500':
          description: Server Error
          examples:
            application/json:
              message: Internal Server error
    put:
      summary: update a specific business
      tags:
        - business
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the business to retrieve
          type: integer
        - in: formData
          name: name
          type: string
          description: Name of business
          required: true
        - in: formData
          name: details
          type: string
          description: Details of business
        - in: formData
          name: location
          type: string
          description: Location of business
        - in: formData
          name: category
          type: string
          description: Category of business
      responses:
        '400':
          description: Invalid input
          examples:
            application/json:
              message: Business Name Missing
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: You need to sign in to continue or sign up to get started
        '500':
          description: Internal Server error
          examples:
            application/json:
              message: An error has occured
        security:
        - weconnect_auth:
            - read: userId
    delete:
      summary: delete a specific business
      tags:
        - business
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the business to delete
          type: integer
      responses:
        '200':
          description: Business deleted
          examples:
            application/json:
              message: Business deleted
        '404':
          description: business not found
          examples:
            application/json:
              message: Business not found

  /businesses/{id}/reviews:
    get:
      tags:
      - reviews
      summary: list reviews
      description: List reviews for  a business
      produces:
      - application/json
      parameters:
      - name: id
        description: id of the business to get reviews
        in: path
        type: integer
        minimum: 1
        required: true
      responses:
        200:
          description: a list of reviews about a business
          examples:
            application/json:
              message: Reviews retrieved successfully
        404:
          description: No reviews
          examples:
            application/json:
              message: No reviews was found for this business
    post:
      tags:
      - reviews
      summary: Add review
      description: Add review of a business
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: id of the business to add review
        type: integer
        minimum: 1
        required: true
      - name: reviewTitle
        in: formData
        description: Title of review
        type: string
        required: true
      - name: reviewName
        in: formData
        description: Name of Reviewer
        type: string
        required: true
      - name: reviewDescription
        in: formData
        description: Content of the review
        type: integer
        required: true

      responses:
        '201':
          description: Created Business Successfully
          examples:
            application/json:
              message: New Business Added
              review:
                reviewTitle: Excellent Job
                reviewName: Godwin Ekuma
                reviewDescription: Something something
        '400':
          description: Invalid input
          examples:
            application/json:
              message: Review Name Missing
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: You need to sign in to continue or sign up to get started
        '500':
          description: Internal Server error
          examples:
            application/json:
              message: An error has occured
        security:
        - weconnect_auth:
            - read:userId
            - read:businessId

  /auth/signin:
    post:
      tags:
      - auth
      summary: login a user
      description: Log in a user to the application
      produces:
      - application/json
      parameters:
      - name: email
        in: formData
        description: email of the user
        type: string
        required: true
      - name: password
        in: formData
        description: password of the user
        type: string
        required: true
      responses:
        '200':
          description: Success, user is logged in
          examples:
            application/json:
              message: 'logged in successfully'
        '401':
          description: Unauthorized
          examples:
            application/json:
              message: Unable to login
        '500':
          description: Internal Server error
          examples:
            application/json:
              message: An error has occured
        security:
        - weconnect_auth:
            - write:userId
           

  /auth/signup:
    post:
      tags:
      - auth
      summary: Signup a user
      description: Signup user into the application
      produces:
      - application/json
      parameters:
      - name: email
        in: formData
        description: email of the user
        type: string
        required: true
      - name: password
        in: formData
        description: password of the user
        type: string
        required: true
      - name: businessName
        in: formData
        description: Name of business
        type: string
        required: true
      - name: businessCategory
        in: formData
        description: category of the business
        type: string
        required: true
      - name: firstName
        in: formData
        description: Firstname of the business owner
        type: string
        required: true
      - name: lastName
        in: formData
        description: Lastname of the business owner
        type: string
        required: true
      responses:
        '201':
          description: Success, user is signed up
          examples:
            application/json:
              message: 'signup in successfully'
        '400':
          description: Invalid input
          examples:
            application/json:
              message: Email Missing
        '403':
          description: Forbidden request
          examples:
            application/json:
              message: User already exist
        '500':
          description: Internal Server error
          examples:
            application/json:
              message: An error has occured
        security:
        - weconnect_auth:
            - write:userId