swagger: '2.0'
info:
  description: >-
    WeConnect provides a platform that brings businesses and individuals together. This platform creates awareness for businesses and gives the users the ability to write reviews about the businesses they have interacted with
  version: 1.0.0
  title: WeConnect Api Documentation
  contact:
    email: godwinekuma@gmail.com
host: geo-we-connect.herokuapp.com
basePath: /api/v1
tags:
  - name: business
    description: Everything about businesses
  - name: review
    description: reviews about a business
  - name: user
    description: Operations about user
schemes:
  - http
  - https
paths:
  /businesses:
    post:
      tags:
        - business
      summary: Add a new business to the database
      description: 'This add a business to the list of businesses in weconnect'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: businessName
          description: business object that needs to be added to the database
          required: true
          schema:
            $ref: '#/definitions/Business'
      responses:
        '200':
          description: Suceess
        '400':
          description: Invalid input
  '/businesses/{businessId}':
    get:
      tags:
        - business
      summary: Find business by ID
      description: Returns a single business
      produces:
        - application/json
      parameters:
        - name: businessId
          in: path
          description: ID of business to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Business'
        '400':
          description: Invalid ID supplied
        '404':
          description: business  not found
    put:
      tags:
        - business
      summary: Updates a business
      description: 'checks if a business exists and updates the business'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: businessName
          description: business object that needs to be added to the database
          required: true
          schema:
            $ref: '#/definitions/Business'
      responses:
        '200':
          description: Update succesful
        '400':
          description: Bad request
        '404':
          description: Business not found
    delete:
      tags:
        - business
      summary: Deletes a business
      description: 'Removes a business from the database'
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: petId
          in: path
          description: business id to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Succesful
        '404':
          description: business  not found
  '/businesses/{businessId}/reviews':
    post:
      tags:
        - business review
      summary: adds a reviews
      description: 'adds a review to a business'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: businessId
          in: path
          description: ID of business to review
          required: true
          type: integer
          format: int64
        - name: reviewTitle
          in: body
          description: Title of review to be added
          required: true
          type: string
        - name: reviewName
          in: body
          description: name of the reviewer
          required: true
          type: string
        - name: reviewDescription
          in: body
          description: Description of the review
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: no such business
    get:
      tags:
        - business review
      summary: Find reviews for a business
      description: ''
      produces:
        - application/json
      parameters:
        - name: businessId
          in: path
          description: ID of business that the reviewsneeds to be fetched
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: no reviews for the business  
  /auth/signup:
    post:
      tags:
        - user
      summary: Create user
      description: ''
      consumes:
        - application/json    
      produces:
        - application/json
      parameters:
        - in: body
          name: businessName
          description: businessName of User
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: success
        '404':
          description: business not found
  /auth/signin:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: email
          in: body
          description: The email for login
          required: true
          type: string
        - name: password
          in: body
          description: The password for login 
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: string
        '400':
          description: Invalid username/password supplied
definitions:
  User:
    type: object
    required:
      - email
      - password
      - businessName
      - businessCategory
      - firstName
      - lastName
    properties:
      email:
        type: string
      password:
        type: string
      businessName:
        type: string
      businessCategory:
        type: string
      firstName:
        type: string
      lastname:
        type: string
  Business:
    type: object
    required:
      - businessName
      - businessEmail
      - businessAddress
    properties:
      id:
        type: integer
        format: int64
      businessName:
        type: string
      businessEmail:
        type: string
        format: email
      businessCategory:
        type: string
      businessWebsite:
        type: string
      businessDescription:
        type: string
      businessAddress:
        type: string
      businessLogo:
        type: string
      businessProfileImage:
        type: string
      products:
        type: array
        items: 
            type: object
  